services:
  magasin:
    container_name: magasin-micro-services
    build:
      context: ./backend/magasin
    volumes:
      - ./backend/magasin:/usr/src/magasin-app
    ports:
      - 3007:3007
    networks:
      - microservice
  
  marchandise:
    container_name: marchandise-micro-services
    build: 
      context: ./backend/marchandises
    volumes:
      - ./backend/marchandises:/usr/src/marchandise-app
    ports:
      - 3012:3012
    networks:
      - microservice

  stockage:
    container_name: stockage-micro-services
    build: 
      context: ./backend/stockage
    volumes:
      - ./backend/stockage:/usr/src/stockage-app
    ports:
      - 3013:3013
    networks:
      - microservice

  auth:
    container_name: auth-micro-services
    build: 
      context: ./backend/auth
    volumes:
      - ./backend/auth:/usr/src/auth-app
    ports:
      - 3010:3010
    networks:
      - microservice

  angular:
    container_name: angular-app
    build:
      context: ./frontend
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - microservice

networks:
  microservice:
    driver: bridge
    external: true